version: '3.8'

services:
  app:
    build: .
    container_name: dolar-dehoy-app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    depends_on:
      - dragonfly
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  dragonfly:
    image: docker.dragonflydb.io/dragonflydb/dragonfly
    container_name: dolar-dehoy-dragonfly
    ports:
      - "6379:6379"
    volumes:
      - dragonfly-data:/data
    command: >
      dragonfly
      --logtostderr
      --requirepass=jesuscestari
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "jesuscestari", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  dragonfly-data:
    driver: local
